
static err_item errs_list[] = {
 { -976, "src/modules/c_zmq/main.c: invalid backend data supplied" },
 { -974, "src/modules/c_zmq/main.c: invalid frontend data supplied" },
 { -950, "src/modules/c_zmq/main.c: backend parameter not supplied" },
 { -947, "src/modules/c_zmq/main.c: frontend parameter not supplied" },
 { -943, "src/modules/c_zmq/main.c: device string invalid" },
 { -938, "src/modules/c_zmq/main.c: device parameter not supplied" },
 { -919, "src/modules/c_zmq/main.c: calloc failed" },
 { -775, "src/modules/c_zmq/main.c: socket parameter not supplied" },
 { -752, "src/modules/c_zmq/main.c: malloc failed" },
 { -744, "src/modules/c_zmq/main.c: calloc failed" },
 { -604, "src/modules/c_zmq/main.c: zmq_msg_init failed" },
 { -504, "src/modules/c_zmq/main.c: zmq_msg_init failed" },
 { -431, "src/modules/c_zmq/main.c: zmq_msg_init failed" },
 { -309, "src/modules/c_zmq/main.c: no bind nor connect supplied in zmq options" },
 { -302, "src/modules/c_zmq/main.c: zmq_connect failed" },
 { -293, "src/modules/c_zmq/main.c: zmq_bind failed" },
 { -281, "src/modules/c_zmq/main.c: zmq_setsockopt int failed" },
 { -269, "src/modules/c_zmq/main.c: zmq_setsockopt int64 failed" },
 { -257, "src/modules/c_zmq/main.c: zmq_setsockopt uint64 failed" },
 { -244, "src/modules/c_zmq/main.c: data_get_continious failed on zmq options" },
 { -241, "src/modules/c_zmq/main.c: zmq_setsockopt binary failed" },
 { -229, "src/modules/c_zmq/main.c: zmq_socket failed" },
 { -195, "src/modules/c_zmq/main.c: data_get_continious failed on zmq options" },
 { -192, "src/modules/c_zmq/main.c: strndup failed" },
 { -178, "src/modules/c_zmq/main.c: The operation was interrupted by delivery of a signal." },
 { -177, "src/modules/c_zmq/main.c: No I/O thread is available to accomplish the task." },
 { -176, "src/modules/c_zmq/main.c: The provided socket was invalid." },
 { -175, "src/modules/c_zmq/main.c: The 0MQ context associated with the specified socket was terminated." },
 { -174, "src/modules/c_zmq/main.c: The requested address specifies a nonexistent interface." },
 { -173, "src/modules/c_zmq/main.c: The requested address was not local." },
 { -172, "src/modules/c_zmq/main.c: The requested address is already in use." },
 { -171, "src/modules/c_zmq/main.c: The requested transport protocol is not compatible with the socket type." },
 { -170, "src/modules/c_zmq/main.c: The requested transport protocol is not supported." },
 { -169, "src/modules/c_zmq/main.c: The endpoint supplied is invalid" },
 { -127, "src/modules/c_zmq/main.c: zmq_init failed" },

	{ 0, NULL }
};
