
static err_item errs_list[] = {
 { -1178, "src/modules/c_zmq/main.c: invalid backend data supplied" },
 { -1176, "src/modules/c_zmq/main.c: invalid frontend data supplied" },
 { -1153, "src/modules/c_zmq/main.c: backend parameter not supplied" },
 { -1150, "src/modules/c_zmq/main.c: frontend parameter not supplied" },
 { -1146, "src/modules/c_zmq/main.c: device string invalid" },
 { -1141, "src/modules/c_zmq/main.c: device parameter not supplied" },
 { -1122, "src/modules/c_zmq/main.c: calloc failed" },
 { -976, "src/modules/c_zmq/main.c: socket parameter not supplied" },
 { -953, "src/modules/c_zmq/main.c: malloc failed" },
 { -945, "src/modules/c_zmq/main.c: calloc failed" },
 { -799, "src/modules/c_zmq/main.c: zmq_msg_init failed" },
 { -705, "src/modules/c_zmq/main.c: zmq_msg_init failed" },
 { -632, "src/modules/c_zmq/main.c: zmq_msg_init failed" },
 { -509, "src/modules/c_zmq/main.c: no bind nor connect supplied in zmq options" },
 { -502, "src/modules/c_zmq/main.c: zmq_connect failed" },
 { -493, "src/modules/c_zmq/main.c: zmq_bind failed" },
 { -481, "src/modules/c_zmq/main.c: zmq_setsockopt int failed" },
 { -469, "src/modules/c_zmq/main.c: zmq_setsockopt int64 failed" },
 { -457, "src/modules/c_zmq/main.c: zmq_setsockopt uint64 failed" },
 { -444, "src/modules/c_zmq/main.c: data_make_flat failed on zmq options" },
 { -441, "src/modules/c_zmq/main.c: zmq_setsockopt binary failed" },
 { -429, "src/modules/c_zmq/main.c: zmq_socket failed" },
 { -395, "src/modules/c_zmq/main.c: data_make_flat failed on zmq options" },
 { -392, "src/modules/c_zmq/main.c: strndup failed" },
 { -378, "src/modules/c_zmq/main.c: The operation was interrupted by delivery of a signal." },
 { -377, "src/modules/c_zmq/main.c: No I/O thread is available to accomplish the task." },
 { -376, "src/modules/c_zmq/main.c: The provided socket was invalid." },
 { -375, "src/modules/c_zmq/main.c: The 0MQ context associated with the specified socket was terminated." },
 { -374, "src/modules/c_zmq/main.c: The requested address specifies a nonexistent interface." },
 { -373, "src/modules/c_zmq/main.c: The requested address was not local." },
 { -372, "src/modules/c_zmq/main.c: The requested address is already in use." },
 { -371, "src/modules/c_zmq/main.c: The requested transport protocol is not compatible with the socket type." },
 { -370, "src/modules/c_zmq/main.c: The requested transport protocol is not supported." },
 { -369, "src/modules/c_zmq/main.c: The endpoint supplied is invalid" },
 { -327, "src/modules/c_zmq/main.c: zmq_init failed" },

};
#define            errs_list_size      sizeof(errs_list[0])
#define            errs_list_nelements sizeof(errs_list) / errs_list_size
