.TH "_goslice_" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_goslice_ \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBarray\fP"
.br
.ti -1c
.RI "unsigned int \fBlen\fP"
.br
.ti -1c
.RI "unsigned int \fBcap\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
