.TH "backend_new_ctx" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend_new_ctx \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlist\fP \fBbackends\fP"
.br
.ti -1c
.RI "\fBbackend_t\fP * \fBbackend_prev\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
