.TH "balancer_userdata" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
balancer_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "balancer_mode \fBmode\fP"
.br
.ti -1c
.RI "\fBhash_t\fP * \fBfork_req\fP"
.br
.ti -1c
.RI "hash_key_t \fBfield\fP"
.br
.ti -1c
.RI "size_t \fBcounter\fP"
.br
.ti -1c
.RI "size_t \fBclone\fP"
.br
.ti -1c
.RI "size_t \fBlinear_len\fP"
.br
.ti -1c
.RI "\fBbackend_t\fP ** \fBlinear_pool\fP"
.br
.ti -1c
.RI "\fBlist\fP * \fBpool\fP"
.br
.ti -1c
.RI "\fBlist\fP \fBown_pool\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
