.TH "buffer_t" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
buffer_t \- 
.PP
\fBbuffer_t\fP structure  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <buffer.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbuff_type\fP \fBtype\fP"
.br
.RI "\fIBuffer type. \fP"
.ti -1c
.RI "size_t \fBsize\fP"
.br
.RI "\fIBuffer length. \fP"
.ti -1c
.RI "void * \fBhead\fP"
.br
.RI "\fIFirst buffer chunk. \fP"
.ti -1c
.RI "void * \fBtail\fP"
.br
.RI "\fILast buffer chunk. \fP"
.ti -1c
.RI "void * \fBio_context\fP"
.br
.RI "\fIIO context. \fP"
.ti -1c
.RI "func_buffer \fBio_read\fP"
.br
.RI "\fIIO read function. \fP"
.ti -1c
.RI "func_buffer \fBio_write\fP"
.br
.RI "\fIIO write function. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBbuffer_t\fP structure 

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
