.TH "Buffers" 3 "Tue Oct 25 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Buffers \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbuffer.c\fP"
.br
.PP

.RI "\fIWorking with \fBbuffer_t\fP. \fP"
.ti -1c
.RI "file \fBbuffer.h\fP"
.br
.PP

.RI "\fIBuffers header. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
