.TH "cacheapp_userdata" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cacheapp_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBinited\fP"
.br
.ti -1c
.RI "\fBmemory_t\fP \fBmemory\fP"
.br
.ti -1c
.RI "\fBbackend_t\fP * \fBbackend\fP"
.br
.ti -1c
.RI "off_t \fBcache_start_offset\fP"
.br
.ti -1c
.RI "size_t \fBcache_max_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
