.TH "cache_userdata" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uintmax_t \fBenabled\fP"
.br
.ti -1c
.RI "\fBmemory_t\fP \fBmemory\fP"
.br
.ti -1c
.RI "\fBdata_t\fP \fBd_memory\fP"
.br
.ti -1c
.RI "pthread_rwlock_t \fBlock\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
