.TH "chm_imp_params_t" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chm_imp_params_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBcapacity\fP"
.br
.ti -1c
.RI "uint64_t \fBnelements\fP"
.br
.ti -1c
.RI "uint64_t \fBhash1\fP"
.br
.ti -1c
.RI "uint64_t \fBhash2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
