.TH "chunk_t" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chunk_t \- 
.PP
\fBchunk_t\fP structure  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <buffer.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBchunk_type\fP \fBtype\fP"
.br
.RI "\fIChunk type. \fP"
.ti -1c
.RI "size_t \fBsize\fP"
.br
.RI "\fIChunk size. \fP"
.ti -1c
.RI "void * \fBcnext\fP"
.br
.RI "\fINext chunk ptr. \fP"
.ti -1c
.RI "void * \fBbare_ptr\fP"
.br
.RI "\fIPtr to raw memory (only CHUNK_TYPE_BARE) \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBchunk_t\fP structure 

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
