.TH "cmdline_option" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline_option \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBOPT_VALUE_INT\fP, \fBOPT_VALUE_STR\fP, \fBOPT_VALUE_BOOL\fP, \fBOPT_FUNC\fP, \fBOPT_GROUP\fP }"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBlong_name\fP"
.br
.ti -1c
.RI "char \fBshort_name\fP"
.br
.ti -1c
.RI "enum cmdline_option:: { ... }  \fBtype\fP"
.br
.ti -1c
.RI "void * \fBopt_ptr\fP"
.br
.ti -1c
.RI "const char * \fBhelpmsg\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
