.TH "data_t" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_t \- 
.PP
Data holder.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uintmax_t \fBtype\fP"
.br
.RI "\fIData type. One of TYPE_*. Use datatype_t to hold this value. \fP"
.ti -1c
.RI "void * \fBptr\fP"
.br
.RI "\fIPointer to data. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data holder. 

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
