.TH "dataptr_t" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataptr_t \- Overview
This data used to hold pointers to data. On read and writes it will return data holder content instead of actual data. 
.SS "Define"
Possible defines: 
.PP
.nf
       data_t hptr = DATA_DATAPTRT(data);

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
