.TH "datatype_t" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatype_t \- Overview
This data used to hold type of data. Valid values are all TYPE_* constants. 
.SS "Define"
Possible defines: 
.PP
.nf
       data_t htype = DATA_DATATYPET(TYPE_UINTT);

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
