.TH "data_proto_t" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_proto_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBtype_str\fP"
.br
.ti -1c
.RI "datatype_t \fBtype\fP"
.br
.ti -1c
.RI "data_api_type \fBapi_type\fP"
.br
.ti -1c
.RI "f_data_func \fBhandler_default\fP"
.br
.ti -1c
.RI "f_data_func \fBhandlers\fP [ACTION_INVALID]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
