.TH "data.c" 3 "Tue Oct 25 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data.c \- 
.PP
Data manipulations.  

.SH SYNOPSIS
.br
.PP
\fC#include <libfrozen.h>\fP
.br
\fC#include <dataproto.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBdata_query\fP (\fBdata_t\fP *data, void *args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data manipulations. 


.SH "Function Documentation"
.PP 
.SS "ssize_t data_query (\fBdata_t\fP *data, void *args)"Call action on data 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Data to process 
.br
\fIargs\fP One of fastcall_* structs, with parameters to data 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI-ENOSYS\fP No such function 
.br
\fI-EINVAL\fP Invalid data passed, or arguments count 
.br
\fI0\fP Call successfull 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
