.TH "dns_entry" 3 "Fri Sep 2 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dns_entry \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBdomain\fP"
.br
.ti -1c
.RI "unsigned int \fBip\fP"
.br
.ti -1c
.RI "unsigned int \fBtimestamp\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
