.TH "emitter_userdata" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emitter_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "emitter_action \fBon_start\fP"
.br
.ti -1c
.RI "emitter_action \fBon_end\fP"
.br
.ti -1c
.RI "\fBhash_t\fP * \fBprereq\fP"
.br
.ti -1c
.RI "\fBhash_t\fP * \fBreq\fP"
.br
.ti -1c
.RI "\fBhash_t\fP * \fBpostreq\fP"
.br
.ti -1c
.RI "uintmax_t \fBnreq\fP"
.br
.ti -1c
.RI "uintmax_t \fBemitter_started\fP"
.br
.ti -1c
.RI "pthread_t \fBemitter_thread\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
