.TH "file_userdata" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "int \fBhandle\fP"
.br
.ti -1c
.RI "size_t \fBflags\fP"
.br
.ti -1c
.RI "size_t \fBbuffer_size\fP"
.br
.ti -1c
.RI "struct stat \fBfile_stat\fP"
.br
.ti -1c
.RI "file_stat_status \fBfile_stat_status\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBcreate_lock\fP"
.br
.ti -1c
.RI "\fBdata_t\fP \fBfile_io\fP"
.br
.ti -1c
.RI "hash_key_t \fBbuffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
