.TH "frozen_userdata" 3 "Fri Sep 2 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frozen_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "frozen_type \fBtype\fP"
.br
.ti -1c
.RI "\fBbackend_t\fP * \fBbackend\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
