.TH "hash_t" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hash_t \- 
.PP
Hash item.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hash.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "hash_key_t \fBkey\fP"
.br
.RI "\fIHash key. \fP"
.ti -1c
.RI "\fBdata_t\fP \fBdata\fP"
.br
.RI "\fIHash value - data holder. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Hash item. 

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
