.TH "hash_t_recomendations" 3 "Fri Oct 28 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hash_t_recomendations \- Recomendations 
.PD 0
.IP "\(bu" 2
Don't mess with clear assignment, just redefine. It is cheap and fast. 
.IP "\(bu" 2
Keep old request inlining. Hash can contain some keys you can't know about, and some backend is waiting them. 
.IP "\(bu" 2
To lower access time to hash keep keys than would be accessed many times as top as possible. That's why action key is at top in most of requests. 
.PP

