.TH "int64_t" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int64_t \- Overview
This data used to hold integers of different size. 
.SS "Define"
Possible defines: 
.PP
.nf
       data_t hint  = DATA_INT64T(100);
        
       int64_t some  = 200;
       data_t hpint = DATA_PTR_INT64T(&some);

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
