.TH "io_t.h" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io_t.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBio_t\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDATA_IOT\fP(_ud, _func)   {TYPE_IOT, (\fBio_t\fP []){ { _ud, _func } }}"
.br
.ti -1c
.RI "#define \fBDEREF_TYPE_IOT\fP(_data)   (\fBio_t\fP *)((_data)->ptr)"
.br
.ti -1c
.RI "#define \fBREF_TYPE_IOT\fP(_dt)   _dt"
.br
.ti -1c
.RI "#define \fBHAVEBUFF_TYPE_IOT\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef ssize_t(* \fBf_io_func\fP )(void *userdata, void *args)"
.br
.RI "\fIIo_t callback. \fP"
.ti -1c
.RI "typedef struct \fBio_t\fP \fBio_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
