.TH "ipc_t" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipc_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbackend_t\fP * \fBbackend\fP"
.br
.ti -1c
.RI "char \fBuserdata\fP [MAX_USERDATA_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
