.TH "ipc_shmem_userdata" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipc_shmem_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBinited\fP"
.br
.ti -1c
.RI "ipc_role \fBrole\fP"
.br
.ti -1c
.RI "forced_states \fBforced_state\fP"
.br
.ti -1c
.RI "hash_key_t \fBbuffer\fP"
.br
.ti -1c
.RI "uintmax_t \fBreturn_result\fP"
.br
.ti -1c
.RI "\fBipc_shmem_header\fP * \fBshmaddr\fP"
.br
.ti -1c
.RI "\fBipc_shmem_block\fP * \fBshmblocks\fP"
.br
.ti -1c
.RI "void * \fBshmdata\fP"
.br
.ti -1c
.RI "pthread_t \fBserver_thr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
