.TH "memory_t" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memory_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "uintmax_t \fBptr_size\fP"
.br
.ti -1c
.RI "uintmax_t \fBexact_size\fP"
.br
.ti -1c
.RI "uintmax_t \fBpage_size\fP"
.br
.ti -1c
.RI "int \fBzero\fP"
.br
.ti -1c
.RI "memory_t_type \fBtype\fP"
.br
.ti -1c
.RI "memory_t_alloc \fBalloc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
