.TH "Backend 'io/stderr'" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend 'io/stderr' \- Description
This backend write to console stderr 
.SS "Configuration"
Accepted configuration: 
.PP
.nf
 {
              class                   = 'io/stderr',
              input                   = (hashkey_t)'buffer'     # input buffer key, default 'buffer'
 }

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
