.TH "Backend 'index/hashtable'" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend 'index/hashtable' \- Description
This is simpliest index avaliable. For given value (i.e. from data hasher backend) it calculate offset in fixed size table and pass request. No chaining, nor collision detection. It more alike bloom filter, but for bigger than bit values. 
.SS "Configuration"
Accepted configuration: 
.PP
.nf
 {
              class                   = 'index/hashtable',
              input                   = (hashkey_t)'keyid', # key for input, default 'key'
              nelements               = (uint_t)'100',      # size of hash table
 }

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
