.TH "Backend 'storage/pointers'" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend 'storage/pointers' \- Pointers module store pointers to data instead of actual data Configuration
Accepted configuration: 
.PP
.nf
   {
                class    = 'storage/pointers',
              input    = 'buffer',             # input data HK
              offset   = 'offset',             # offset HK
        }

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
