.TH "Backend 'io/stdin'" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend 'io/stdin' \- Description
This backend read from console 
.SS "Configuration"
Accepted configuration: 
.PP
.nf
 {
              class                   = 'io/stdin',
              action                  = (action_t)'write',       # action to emit, default 'write'
              output                  = (hashkey_t)'buffer',     # output buffer key, default 'buffer'
              destroy                 = (uint_t)'1'              # send SEGTERM on stdin eof, default 0
 }

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
