.TH "Backend 'storage/file'" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend 'storage/file' \- File module can read and write to file Configuration
Accepted configuration: 
.PP
.nf
   {
                class    = 'file',
                filename = 'somefilename.dat',        # produce {homedir}{filename} file
              filename = {                          # produce concat'ed string from following components:
                           homedir => (void_t)'',   #  - {homedir}
                           string  => 'somename',   #  - any string, any times
                           string  => '.dat',       #
                           random  => 'AAAA',       #  - random string [a-zA-Z0-9] of length 4
                           fork    => 'keyname'     #  - key from fork request array, strings only. Skipped on non-fork requests
                         },
              buffer_size = (size_t)'1024',         # default buffer size for move operation
              readonly    = (size_t)'1',            # make file read-only, default is read-write
              exclusive   = (size_t)'1',            # pass O_EXCL for open, see man page
              create      = (size_t)'1',            # pass O_CREAT for open, see man page
              mode        = (size_t)'0777',         # file mode on creation. TODO octal representation
              retry       = (size_t)'1',            # regen filename and retry open. usefull for example for tmpname generation
              fork_only   = (size_t)'1',            # open new file only on forks
        }

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
