.TH "Backend 'request/explode'" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend 'request/explode' \- Description
This backend unpack new request from current request. Useful for ipc. See \fBBackend 'request/implode'\fP for packing.
.PP
Unpacking process use data _CONVERT_FROM functions, and _CONVERT_TO for result returning. All data types used in request have to support them. 
.SS "Configuration"
Accepted configuration: 
.PP
.nf
 {
              class                   = 'request/explode',
              buffer                  = (hashkey_t)'buffer',  # key name in new request
              return_result           = (uint_t)'0',          # pack changed, during further processing, request back to old one, default 1
 }

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
