.TH "Backend 'data/list'" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend 'data/list' \- Description
This backend simulate list of values. On writing item to <offset> it move all values from <offset> to <offset>+1. On delete it do reverse operation.
.PP
User request must have \fBHK(insert)\fP set for this.
.PP
This module works in pair with 'insert_sort' to provide clean inserts to file. This module move data on 1 (one) unit - use 'incapsulate' to move for valid length. 
.SS "Configuration"
Accepted configuration: 
.PP
.nf
 {
              class                   = 'data/list',
 }

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
