.TH "Backend 'cache/cache'" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend 'cache/cache' \- Cache module hold data in memory, instead of underlying backend Cache configuration
Accepted configuration: 
.PP
.nf
     {
                class         = 'cache'
        }

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
