.TH "Backend 'io/fuse'" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend 'io/fuse' \- Description
This backend add fuse filesystem support for frozen. You can use it as input and output for any backend. 
.SS "Configuration"
Accepted configuration: 
.PP
.nf
 {
              class                   = 'io/fuse',
              mountpoint              = '/mnt/somepoint/',  # mountpoint for fuse fs
              multithread             = (uint_t)'1',        # enable multithreaded fuse operations, default 0 // NOTE don't use it until all backends would be multithread-capable
              items                   = {                   # define files and folders to create in fs
                   {                                        # - first example item
                       path           = '/onefile',         #     full relative path to file/folder starting with /
                       folder         = (uint_t)'1',        #     is it folder?, default 0
                       backend        = (backend_t)'bname'  #     backend for request sending
                   },
                   ...
              }
 }

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
