.TH "Backend 'data/structs'" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend 'data/structs' \- Description
This backend pack and unpack user requests accoring defined structure. 
.SS "Configuration"
Accepted configuration: 
.PP
.nf
 {
              class                   = 'data/structs',
              buffer                  = (hashkey_t)'buffer', # input/output request key name, default 'buffer'
              values                  = (hashkey_t)'some',   # if supplied - request key name to take/write values from/to, default take from request
              size                    = (hashkey_t)'size',   # if supplied - add size of packed structure to request with key
              structure               = {                    # structure to pack/unpack to/from
                     keyname = (uint_t)'10',                 # - first field is keyname with default value of 10
                     key2    = (string_t)'',                 # - second field is string
                     ...
              }
 }

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
