.TH "Modules" 3 "Thu Oct 27 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Modules \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBModule 'pool'\fP"
.br
.ti -1c
.RI "\fBModule 'backend/rebuild'\fP"
.br
.ti -1c
.RI "\fBModule 'cache'\fP"
.br
.ti -1c
.RI "\fBModule 'data/regexp'\fP"
.br
.ti -1c
.RI "\fBModule 'index/fill'\fP"
.br
.ti -1c
.RI "\fBModule 'index/lookup'\fP"
.br
.ti -1c
.RI "\fBModule 'balancer'\fP"
.br
.PP

.RI "\fIBalancer module. \fP"
.ti -1c
.RI "\fBModule 'rewrite'\fP"
.br
.ti -1c
.RI "\fBModule 'switch'\fP"
.br
.PP

.RI "\fISwitch module. \fP"
.ti -1c
.RI "\fBModule 'file'\fP"
.br
.ti -1c
.RI "\fBModule 'pointers'\fP"
.br
.PP

.RI "\fIPointers module. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpool.c\fP"
.br
.PP

.RI "\fIPool module. \fP"
.ti -1c
.RI "file \fBcache.c\fP"
.br
.PP

.RI "\fICache module. \fP"
.ti -1c
.RI "file \fBrewrite.c\fP"
.br
.PP

.RI "\fIRewrite module. \fP"
.ti -1c
.RI "file \fBfile.c\fP"
.br
.PP

.RI "\fIFile module. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
