.TH "mphf_t" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mphf_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBconfig_t\fP * \fBconfig\fP"
.br
.ti -1c
.RI "void * \fBbuild_data\fP"
.br
.ti -1c
.RI "mphf_hash_proto_t * \fBhash\fP"
.br
.ti -1c
.RI "char \fBdata\fP [20 *sizeof(void *)]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
