.TH "mphf_userdata" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mphf_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmphf_t\fP \fBmphf\fP"
.br
.ti -1c
.RI "\fBmphf_proto_t\fP * \fBmphf_proto\fP"
.br
.ti -1c
.RI "uintmax_t \fBbroken\fP"
.br
.ti -1c
.RI "hash_key_t \fBinput\fP"
.br
.ti -1c
.RI "hash_key_t \fBoutput\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
