.TH "pool_userdata" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pool_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uintmax_t \fBcreated_on\fP"
.br
.ti -1c
.RI "uintmax_t \fBusage_parameter\fP"
.br
.ti -1c
.RI "uintmax_t \fBusage_ticks_last\fP"
.br
.ti -1c
.RI "uintmax_t \fBusage_ticks_curr\fP"
.br
.ti -1c
.RI "uintmax_t \fBusage_ticks_time\fP"
.br
.ti -1c
.RI "\fBlist\fP * \fBperfork_childs\fP"
.br
.ti -1c
.RI "\fBlist\fP \fBperfork_childs_own\fP"
.br
.ti -1c
.RI "parameter_method \fBparameter\fP"
.br
.ti -1c
.RI "\fBhash_t\fP * \fBparameter_request\fP"
.br
.ti -1c
.RI "uintmax_t \fBtick_interval\fP"
.br
.ti -1c
.RI "\fBrule\fP \fBrule_one\fP"
.br
.ti -1c
.RI "\fBrule\fP \fBrule_perfork\fP"
.br
.ti -1c
.RI "\fBrule\fP \fBrule_global\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
