.TH "regexp_userdata" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
regexp_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBregexp_str\fP"
.br
.ti -1c
.RI "uintmax_t \fBcflags\fP"
.br
.ti -1c
.RI "uintmax_t \fBeflags\fP"
.br
.ti -1c
.RI "hash_key_t \fBinput\fP"
.br
.ti -1c
.RI "hash_key_t \fBmarker\fP"
.br
.ti -1c
.RI "\fBdata_t\fP * \fBmarker_data\fP"
.br
.ti -1c
.RI "uintmax_t \fBcompiled\fP"
.br
.ti -1c
.RI "regex_t \fBregex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
