.TH "rewrite_action_t" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rewrite_action_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBid\fP"
.br
.ti -1c
.RI "rewrite_actions \fBaction\fP"
.br
.ti -1c
.RI "\fBrewrite_thing_t\fP * \fBparams\fP"
.br
.ti -1c
.RI "\fBrewrite_thing_t\fP * \fBret\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
