.TH "rewrite_stack_frame_t" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rewrite_stack_frame_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrewrite_action_block_t\fP * \fBablock\fP"
.br
.ti -1c
.RI "\fBrewrite_action_t\fP * \fBaction\fP"
.br
.ti -1c
.RI "unsigned int \fBaction_id\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
