.TH "rewrite_script_t" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rewrite_script_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBscript\fP"
.br
.ti -1c
.RI "\fBrewrite_action_block_t\fP * \fBmain\fP"
.br
.ti -1c
.RI "\fBrewrite_variable_t\fP * \fBconstants\fP"
.br
.ti -1c
.RI "unsigned int \fBconstants_count\fP"
.br
.ti -1c
.RI "unsigned int \fBvariables_count\fP"
.br
.ti -1c
.RI "unsigned int \fBrequests_count\fP"
.br
.ti -1c
.RI "\fBrewrite_name_t\fP * \fBnames\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
