.TH "rule" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rule \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uintmax_t \fBlimit\fP"
.br
.ti -1c
.RI "choose_method \fBmode\fP"
.br
.ti -1c
.RI "action_method \fBaction\fP"
.br
.ti -1c
.RI "\fBrequest_t\fP * \fBaction_request\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
