.TH "sorts_userdata" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sorts_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbackend_t\fP * \fBbackend\fP"
.br
.ti -1c
.RI "\fBsort_proto_t\fP * \fBengine\fP"
.br
.ti -1c
.RI "hash_key_t \fBsort_field\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
