.TH "string_t" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string_t \- Overview
This data used to hold C strings. 
.SS "Define"
Possible defines: 
.PP
.nf
       data_t str1 = DATA_STRING('hello');
       data_t str2 = DATA_STRING(str_ptr);

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
