.TH "struct_iter_ctx" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
struct_iter_ctx \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrequest_t\fP * \fBvalues\fP"
.br
.ti -1c
.RI "off_t \fBcurr_offset\fP"
.br
.ti -1c
.RI "\fBdata_t\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "uintmax_t \fBbuffer_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
