.TH "swig_type_info" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swig_type_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBstr\fP"
.br
.ti -1c
.RI "swig_dycast_func \fBdcast\fP"
.br
.ti -1c
.RI "struct \fBswig_cast_info\fP * \fBcast\fP"
.br
.ti -1c
.RI "void * \fBclientdata\fP"
.br
.ti -1c
.RI "int \fBowndata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
