.TH "swig_module_info" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swig_module_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBswig_type_info\fP ** \fBtypes\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "struct \fBswig_module_info\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBswig_type_info\fP ** \fBtype_initial\fP"
.br
.ti -1c
.RI "\fBswig_cast_info\fP ** \fBcast_initial\fP"
.br
.ti -1c
.RI "void * \fBclientdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
