.TH "swig_variable_info" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swig_variable_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "SwigMagicFunc \fBset\fP"
.br
.ti -1c
.RI "SwigMagicFunc \fBget\fP"
.br
.ti -1c
.RI "\fBswig_type_info\fP ** \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
