.TH "swig_constant_info" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swig_constant_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "long \fBlvalue\fP"
.br
.ti -1c
.RI "double \fBdvalue\fP"
.br
.ti -1c
.RI "void * \fBpvalue\fP"
.br
.ti -1c
.RI "\fBswig_type_info\fP ** \fBptype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
