.TH "uint8_t" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uint8_t \- Overview
This data used to hold integers of different size. 
.SS "Define"
Possible defines: 
.PP
.nf
       data_t hint  = DATA_UINT8T(100);
        
       uint8_t some  = 200;
       data_t hpint = DATA_PTR_UINT8T(&some);

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
