.TH "vfs_root_userdata" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vfs_root_userdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct fuse * \fBfuse\fP"
.br
.ti -1c
.RI "struct fuse_chan * \fBch\fP"
.br
.ti -1c
.RI "char * \fBmountpoint\fP"
.br
.ti -1c
.RI "pthread_t \fBfs_thread\fP"
.br
.ti -1c
.RI "uintmax_t \fBfs_thread_ok\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
