.TH "virtfs_item" 3 "Fri Sep 2 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
virtfs_item \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBvirtfs_item\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBvirtfs_item\fP * \fBchilds\fP"
.br
.ti -1c
.RI "virt_type \fBtype\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBfullname\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "struct stat \fBstat\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
