.TH "void_t" 3 "Tue Nov 8 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
void_t \- Overview
This data used to represent empty value. 
.SS "Define"
Possible defines: 
.PP
.nf
       data_t hvoid = DATA_VOID;

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
