.TH "yy_buffer_state" 3 "Sat Nov 5 2011" "Version 1.0" "frozen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yy_buffer_state \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "FILE * \fByy_input_file\fP"
.br
.ti -1c
.RI "char * \fByy_ch_buf\fP"
.br
.ti -1c
.RI "char * \fByy_buf_pos\fP"
.br
.ti -1c
.RI "yy_size_t \fByy_buf_size\fP"
.br
.ti -1c
.RI "int \fByy_n_chars\fP"
.br
.ti -1c
.RI "int \fByy_is_our_buffer\fP"
.br
.ti -1c
.RI "int \fByy_is_interactive\fP"
.br
.ti -1c
.RI "int \fByy_at_bol\fP"
.br
.ti -1c
.RI "int \fByy_bs_lineno\fP"
.br
.ti -1c
.RI "int \fByy_bs_column\fP"
.br
.ti -1c
.RI "int \fByy_fill_buffer\fP"
.br
.ti -1c
.RI "int \fByy_buffer_status\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fByy_bs_column\fP"The column count. 
.SS "int \fByy_bs_lineno\fP"The line count. 

.SH "Author"
.PP 
Generated automatically by Doxygen for frozen from the source code.
