#!/bin/sh

folder=src/libfrozen/data/enum/action
action_h=$folder/action.h
action_tmp1=$folder/action.tmp1
action_tmp2=$folder/action.tmp2
action_tmp3=$folder/action.tmp3

rm $action_h 2>/dev/null

keys=`grep "ACTION([A-Za-z0-9_]*)" -roha ./ | sed "s/ACTION(//g" | sed "s/)//g"  | LC_ALL=C sort -u`

i=0
for key in $keys; do
	echo "#define ACTION_VALUE_$key $i"     >> $action_tmp1
	echo "      ACTION_$key = ACTION_VALUE_$key, "  >> $action_tmp2
	echo "      { \"$key\", ACTION_VALUE_$key }, "    >> $action_tmp3
	
	i=$(( $i + 1 ))
done

echo "/* Autogenerated file. Don't edit */" > $action_h
echo "#ifndef ACTIONS_H" >> $action_h
echo "#define ACTIONS_H" >> $action_h
	echo "#define ACT" "ION(value)         ACTION_VALUE_##value" >> $action_h
	cat $action_tmp1 >> $action_h
	echo "typedef enum action_t {" >> $action_h
		cat $action_tmp2 >> $action_h
	echo "      ACTION_INVALID = $i" >> $action_h
	echo "} action_t;" >> $action_h
echo "#endif" >> $action_h
echo "" >> $action_h
echo "#ifdef ACTION_C" >> $action_h
	echo "keypair_t actions[] = {" >> $action_h
		cat $action_tmp3 >> $action_h
	echo "      { NULL, 0 }  " >> $action_h
	echo "};" >> $action_h
echo "#endif" >> $action_h

rm $action_tmp1 $action_tmp2 $action_tmp3 2>/dev/null
