/* Autogenerated file. Don't edit */
#ifndef DATA_SELECTED_ENUM_H
#define DATA_SELECTED_ENUM_H
typedef enum data_type {
   TYPE_INVALID = 0, 
   TYPE_BACKENDT = 1,
   TYPE_BINARYT = 21,
   TYPE_BUFFERT = 22,
   TYPE_HASHT = 17,
   TYPE_IOT = 3,
   TYPE_MEMORYT = 18,
   TYPE_RAWT = 19,
   TYPE_STRINGT = 16,
   TYPE_STRUCTT = 2,
   TYPE_OFFT = 13,
   TYPE_SIZET = 12,
   TYPE_UINTT = 14,
   TYPE_INTT = 15,
   TYPE_INT8T = 4,
   TYPE_INT16T = 5,
   TYPE_INT32T = 6,
   TYPE_INT64T = 7,
   TYPE_UINT8T = 8,
   TYPE_UINT16T = 9,
   TYPE_UINT32T = 10,
   TYPE_UINT64T = 11,
   TYPE_VOIDT = 20,
} data_type;
#endif
