/* Autogenerated file. Don't edit */
#ifndef HASHKEYS_H
#define HASHKEYS_H

typedef uintmax_t hash_key_t;

#define HASH_KEY_action 1
#define HASH_KEY_backend 2
#define HASH_KEY_backend_e 3
#define HASH_KEY_backend_g 4
#define HASH_KEY_backend_v 5
#define HASH_KEY_backends 6
#define HASH_KEY_block_off 7
#define HASH_KEY_block_size 8
#define HASH_KEY_block_vid 9
#define HASH_KEY_blocks 10
#define HASH_KEY_buffer 11
#define HASH_KEY_buffer_size 12
#define HASH_KEY_chains 13
#define HASH_KEY_count 14
#define HASH_KEY_dns_domain 15
#define HASH_KEY_dns_ip 16
#define HASH_KEY_dns_tstamp 17
#define HASH_KEY_engine 18
#define HASH_KEY_field 19
#define HASH_KEY_filename 20
#define HASH_KEY_forced 21
#define HASH_KEY_function 22
#define HASH_KEY_handle 23
#define HASH_KEY_hash 24
#define HASH_KEY_homedir 25
#define HASH_KEY_insert 26
#define HASH_KEY_item_size 27
#define HASH_KEY_key 28
#define HASH_KEY_key_from 29
#define HASH_KEY_key_out 30
#define HASH_KEY_key_to 31
#define HASH_KEY_keyid 32
#define HASH_KEY_max_rebuilds 33
#define HASH_KEY_multiply 34
#define HASH_KEY_n_initial 35
#define HASH_KEY_name 36
#define HASH_KEY_nelements 37
#define HASH_KEY_offset 38
#define HASH_KEY_offset_from 39
#define HASH_KEY_offset_out 40
#define HASH_KEY_offset_to 41
#define HASH_KEY_param 42
#define HASH_KEY_path 43
#define HASH_KEY_perlevel 44
#define HASH_KEY_read_size 45
#define HASH_KEY_real_offset 46
#define HASH_KEY_role 47
#define HASH_KEY_script 48
#define HASH_KEY_size 49
#define HASH_KEY_size_old 50
#define HASH_KEY_structure 51
#define HASH_KEY_type 52
#define HASH_KEY_value 53
#define HASH_KEY_value_bits 54
#define HASH_KEY_values 55
#endif
