/* Autogenerated file. Don't edit */
#ifndef HASHKEYS_INT_H
#define HASHKEYS_INT_H

typedef struct hash_keypair_t {
    char *        key_str;
    hash_key_t    key_val;
} hash_keypair_t;

extern hash_keypair_t hash_keys[];
extern size_t hash_keys_size;
extern size_t hash_keys_nelements;

#endif
