m4_include(data/void.c)
m4_include(data/binary.c)
m4_include(data/uint8.c)
m4_include(data/uint16.c)
m4_include(data/uint32.c)
m4_include(data/uint64.c)
m4_include(data/size_t.c)
m4_include(data/off_t.c)
m4_include(data/string.c)
m4_include(data/hash_t.c)
m4_include(data/buffer_t.c)
m4_include(data/io_t.c)

